### ISSUE TITLE
Partially not working if you switch pixiv language to english

### ISSUE THREAD

**Issue by r00teniy** [Ocrosoft/PixivPreviewer#1]
Hello, if you switch pixiv language to english it will replace some urls, for example artworks becomes "https://www.pixiv.net/en/artworks/" and users "https://www.pixiv.net/en/users" which wold make this script not work for these pages. 
It would be nice if you could add support for eng version as well.

**Comment by Ocrosoft** [comment]
The latest version has fixed this bug, update please.
