### ISSUE TITLE
「Bug」预览图随鼠标移动难以点击

### ISSUE THREAD

**Issue by BoruiGu** [Ocrosoft/PixivPreviewer#10]
预览图会随着鼠标移动导致难以点击到，造成通过点击来翻页变得困难（要很快移动鼠标才能赶上预览图的移动）

**Comment by Ocrosoft** [comment]
> 预览图会随着鼠标移动导致难以点击到，造成通过点击来翻页变得困难（要很快移动鼠标才能赶上预览图的移动）

可以按住Ctrl或者鼠标中键，预览图就不会移动了
