### ISSUE TITLE
缩略图展示全尺寸图片功能可以应用在用户投稿页面吗？

### ISSUE THREAD

**Issue by shamashii** [Ocrosoft/PixivPreviewer#11]
https://www.pixiv.net/users/xxx
https://www.pixiv.net/users/xxx/illustrations

**Comment by Ocrosoft** [comment]
> https://www.pixiv.net/users/xxx https://www.pixiv.net/users/xxx/illustrations

理论上可行，得试试看

**Comment by Ocrosoft** [comment]
Dev版现在已经支持用户页，安装后在设置中打开“全尺寸缩略图”开关就可以了。
