### ISSUE TITLE
你好，关注的人投稿页面脚本失效，另外缩略图改善功能能添加此页面吗

### ISSUE THREAD

**Issue by x151973** [Ocrosoft/PixivPreviewer#16]
https://www.pixiv.net/bookmark_new_illust.php

**Comment by Ocrosoft** [comment]
关注页之前没有全量，我这里看到还是旧版页面，所以没办法更新。
现在貌似全量了，dev版已经支持。

**Comment by Ocrosoft** [comment]
GreasyFork 已更新 v3.7.3.
