### ISSUE TITLE
[Bug] 搜索这个小众 keyword 时页面会显示 "没有可以显示的作品"

### ISSUE THREAD

**Issue by HaloWang** [Ocrosoft/PixivPreviewer#19]
[风之谷](https://www.pixiv.net/en/tags/%E9%A3%8E%E4%B9%8B%E8%B0%B7/artworks?s_mode=s_tag)

脚本 version: 3.7.5
搜索 keyword: 风之谷
url: https://www.pixiv.net/en/tags/%E9%A3%8E%E4%B9%8B%E8%B0%B7/artworks?s_mode=s_tag

我当然知道要想得到更多结果不应该用中文 Keyword, 但这应该是个 bug 吧?

**Comment by Ocrosoft** [comment]
设置了隐藏收藏数吧，如果所有作品都低于设置的收藏数，就会显示没有作品。

**Comment by HaloWang** [comment]
哦, thx, 我把这个给忘了. 不如优化一下`没有可以显示的作品`吧?

比如, `没有可以显示的作品, 或您在设定中隐藏了收藏数小于${count}的作品`

**Comment by Ocrosoft** [comment]
确实

**Comment by Ocrosoft** [comment]
@HaloWang 最新版本会显示隐藏了作品：
![image](https://user-images.githubusercontent.com/25629637/162021380-be712dfe-687f-47dc-a7e7-580fb9613660.png)
