### ISSUE TITLE
【功能申请】可以让收藏排序也支持小说页吗？

### ISSUE THREAD

**Issue by zx2kk** [Ocrosoft/PixivPreviewer#2]
如题，如果可以办到的话就太好了……

**Comment by Ocrosoft** [comment]
理论上可以支持，加这么一个新功能工作量比较大，后续再考虑支持吧。

**Comment by sunoleev** [comment]
同蹲一下这个功能！
市面Pixiv插件没有支持小说版块的真的心里苦……希望大佬拯救一下我们！
无论如何等待理论实践的那一天！感恩！！！

**Comment by Ocrosoft** [comment]
> 如题，如果可以办到的话就太好了……



> 同蹲一下这个功能！
> 市面Pixiv插件没有支持小说版块的真的心里苦……希望大佬拯救一下我们！
> 无论如何等待理论实践的那一天！感恩！！！

正在尝试，时间问题近期应该是不会上的。

**Comment by Ocrosoft** [comment]
@zx2kk @sunoleev 
发布了体验版，可前往https://github.com/Ocrosoft/PixivPreviewer/releases安装3.6.0版本。
如发现bug请反馈。

**Comment by sunoleev** [comment]
> @zx2kk @sunoleev
> 发布了体验版，可前往https://github.com/Ocrosoft/PixivPreviewer/releases 安装3.6.0版本。
> 如发现bug请反馈。

感恩大佬！！
目前使用流畅没有发现问题！

**Comment by zx2kk** [comment]
> @ zx2kk @sunoleev
> 发布了体验版，可前往https://github.com/Ocrosoft/PixivPreviewer/releases安装3.6.0版本
> 。

非常感谢，居然真的有了，帮了好大的忙。
大致用了一下，基础功能没什么问题，就是搜索逻辑好像跟插画页面不太一样？如果设置了搜索100页就真的只会搜完100页再显示，哪怕实际上只有个位数的作品符合条件，插画页面的话不会这样，插画页面是搜到全部作品了就开始排序，不会搜多余的页数。
另外【排序时隐藏已收藏的作品】和【排序时隐藏已关注画师作品】的支持似乎还没做？其他功能对小说页意义不大，但这两个功能还是很有用的。
目前就这些意见。

**Comment by Ocrosoft** [comment]
@zx2kk 是的，确实有这个问题，小说排序和插画排序时两个独立的功能，刚开始打算独立成一个脚本，后面觉得同时安装两个比较麻烦还是整合在一起。隐藏作品这两个功能暂时还没有安排，之后有空了再补上。

**Comment by zx2kk** [comment]
> @zx2kk 是的，确实有这个问题，小说排序和插画排序是两个独立的功能，刚开始打算独立成一个脚本，后面觉得同时安装两个比较麻烦还是整合在一起。 隐藏作品这两个功能暂时还没有安排，之后有空了再补上。

打扰了，似乎因为P站的更新，插件出了BUG，现在的小说排序功能，计算完页数后会无限转圈显示【正在按收藏量排序】，请问还会修复吗？

**Comment by Ocrosoft** [comment]
> > @zx2kk 是的，确实有这个问题，小说排序和插画排序是两个独立的功能，刚开始打算独立成一个脚本，后面觉得同时安装两个比较麻烦还是整合在一起。 隐藏作品这两个功能暂时还没有安排，之后有空了再补上。
> 
> 打扰了，似乎因为P站的更新，插件出了BUG，现在的小说排序功能，计算完页数后会无限转圈显示【正在按收藏量排序】，请问还会修复吗？

已修复，GreasyFork安装即可
https://greasyfork.org/zh-CN/scripts/430139

**Comment by zx2kk** [comment]
> 已修复，GreasyFork安装即可
> https://greasyfork.org/zh-CN/scripts/430139

感谢！这下就又能用了！

**Comment by Ocrosoft** [comment]
其他功能后续再补充~
