### ISSUE TITLE
与 PixivBatchDownloader 同时使用时引发的一些冲突

### ISSUE THREAD

**Issue by Hakoyu** [Ocrosoft/PixivPreviewer#20]
PixivPreviewer 的排序方式会导致 [PixivBatchDownloader](https://github.com/xuejianxianzun/PixivBatchDownloader) 一些功能失效
我已经在 PixivBatchDownloader 那边提交过这个问题 详情可以查看 [issues](https://github.com/xuejianxianzun/PixivBatchDownloader/issues/212)

**Comment by Ocrosoft** [comment]
https://github.com/Ocrosoft/PixivPreviewer/releases/tag/3.7.8
