### ISSUE TITLE
[bug]排序无法使用 而且是很多人都在反馈

### ISSUE THREAD

**Issue by Kirietoan** [Ocrosoft/PixivPreviewer#22]
排序无法使用 而且是很多人都在反馈 无关浏览器
填写数值只要大于0再搜索 就会显示无任何结果

**Comment by Ocrosoft** [comment]
根本原因是拉取一百多个收藏量数据，疑似触发了p站api的爬虫风控，导致账号被拉黑，至于具体策略则不清楚。
目前来看这个问题不好处理。。

**Comment by woeijiunn88** [comment]
排序是可以使用，但爬了之后开 artwork 连接会显示没图，
每爬一次账号会被封 5 分钟。

**Comment by Ocrosoft** [comment]
> 排序是可以使用，但爬了之后开 artwork 连接会显示没图， 每爬一次账号会被封 5 分钟。 手机端在这时候完全无法使用。

是的，要是封账号还好，可以想想办法，要是封 ip 直接没辙，估计得换三方 api 了

**Comment by yyyyyyounger** [comment]
同樣遇到這個問題，點擊標籤進入後賬號被封禁5分鐘
![image](https://user-images.githubusercontent.com/55580370/185776175-1b180022-86d0-4eb7-a7bf-965788f3cbf1.png)

作品詳情也無法顯示：
![image](https://user-images.githubusercontent.com/55580370/185776185-e5839490-bcdf-46d2-85ea-a1c1b54e3c96.png)

**Comment by HaloWang** [comment]
很久之前(6个月?)我就发现似乎存在这种限制了. 当时我想的是能否根据 artwork_id 缓存收藏数量. 我的需求是将某个 tag 下的全部时期作品按照收藏数全部排序. 这样的话, 我对某个作品的 “喜欢数” 的实时程度要求就很低, 甚至数以年记. 当然...最后的最后, 还有 pixiv premium 这种收费服务呢 只不过, 我用 pixiv previewer 的频度也不是很高. 有时候心血来潮可能多搜搜

**Comment by Ocrosoft** [comment]
> 很久之前(6个月?)我就发现似乎存在这种限制了. 当时我想的是能否根据 artwork_id 缓存收藏数量. 我的需求是将某个 tag 下的全部时期作品按照收藏数全部排序. 这样的话, 我对某个作品的 “喜欢数” 的实时程度要求就很低, 甚至数以年记. 当然...最后的最后, 还有 pixiv premium 这种收费服务呢 只不过, 我用 pixiv previewer 的频度也不是很高. 有时候心血来潮可能多搜搜

本地缓存对其他人没有效果，如果放到服务器上是有法律风险的；搞这个脚本的目的是让偶尔用用搜索的人不用开 Premium（虽然一个月 30 不贵），因为我自己也可能一个月都用不到这个脚本，顶多每天打开手机版看一眼关注的人。对于画师等常用搜索功能的人，还是非常推荐开 Premium 的。

**Comment by Ocrosoft** [comment]
目前看 anonymous 的方案还是可行的，先关闭 issue。
