### ISSUE TITLE
关于预览图加载视频or动图卡死

### ISSUE THREAD

**Issue by yorisona** [Ocrosoft/PixivPreviewer#24]
可能是内存溢出导致页面直接卡死,建议加一个加载大小限制或者禁止预览视频

**Comment by LolipopJ** [comment]
可以加一个设置项，是否允许 Gif 图或预览视频加载。悬浮预览时很容易出现加载 Gif 图卡死的现象……

**Comment by Ocrosoft** [comment]
3.7.11 添加了对动图的开关，可以关闭动图预览。
