### ISSUE TITLE
[Bug] Tag 页预览功能支持

### ISSUE THREAD

**Issue by LolipopJ** [Ocrosoft/PixivPreviewer#25]
![image](https://user-images.githubusercontent.com/42314340/196219326-142fe32c-931b-403b-a844-e7402e41cd79.png)

Tag 页也包含一些可以预览的图片，例如[此页面](https://www.pixiv.net/tags/%E6%9D%8F%E5%B1%B1%E3%82%AB%E3%82%BA%E3%82%B5)，可以加上预览功能。

**Comment by LolipopJ** [comment]
在标签页面进行刷新操作的话，将无法进行预览操作（没有初始化）。从主页切换路由进入标签页的话，功能正常。

**Comment by Ocrosoft** [comment]
已经在 master 分支修复，将在测试稳定后发布到 greasyfork。
