### ISSUE TITLE
[bug]登陆异常,登陆刷新后又要重新登陆

### ISSUE THREAD

**Issue by Srtvk** [Ocrosoft/PixivPreviewer#26]

**Comment by xushet** [comment]
+1同样遇到这种情况，刷新一下又要重新登陆

**Comment by Ocrosoft** [comment]
@Srtvk @xushet 
这个问题我还是没有遇到过，看 GreasyFork 的评论，可以试试是否与暴力猴有关？

**Comment by Ocrosoft** [comment]
用暴力猴试了一下确实有问题，可以先换 TamperMonkey，这个问题不一定好解决。

**Comment by Ocrosoft** [comment]
看起来是暴力猴在返回 set-cookie 的时候把原 cookie 覆盖了，这个只能等暴力猴那边解决了。

**Comment by Ocrosoft** [comment]
暴力猴的 v2.13.9 版本修复了这个问题。
