### ISSUE TITLE
[建议]添加排除AI作画的功能

### ISSUE THREAD

**Issue by kukukumiko-git** [Ocrosoft/PixivPreviewer#29]
希望添加排除AI作画功能
虽然作品现在有了可以选择是否为AI作画的选项，但是这个选项不能作为搜索的tag，也让很多AI作品不再另外打上AI的tag
因此不能通过排除某个tag在搜索结果中去掉AI
![捕获](https://user-images.githubusercontent.com/114204641/216814735-4624f863-9a89-4083-82ed-b8e790a29eb1.JPG)

**Comment by libaibaba** [comment]
因为可以直接在个人设置里关掉，你点一下ai生成，p站就会教你怎么关

**Comment by kukukumiko-git** [comment]
我去是我火星了。。
