### ISSUE TITLE
考虑把会员账号挂在服务器上用来帮普通用户解析？

### ISSUE THREAD

**Issue by Nevidebla** [Ocrosoft/PixivPreviewer#34]
之前确实有作者这样操作过
https://github.com/zhuzemin/pixiv_sort_by_popularity
只不过目前这个处于失效状态。
原理就跟百度云高速链接解析一样，把一个会员账号挂在服务器上共享出来，拦截普通用户的请求，转到你的服务器去请求P站，然后再把结果返回。在官方看来你只是一个重度的忠实用户而已。
就算会员账号也有频率限制，对于搜索这种低频需求，一般也够用了吧。
就算真不够用，后期规模扩大后也可以略微收费或者带个广告来平衡成本。

**Comment by Ocrosoft** [comment]
之前提过类似的方案，确实是一种实现按热门度排序的办法，结果也比现在更好，就是不太安全，很容易封和警告。
现在的方案虽然不能在整体作品中进行排序，但对于日常使用足够了。
有不少爬虫实现的第三方app，也可以做到不需要会员按热门度排序。
现在还没有足够的理由去做这个方案，难免遇到盈利的问题，这个脚本是因为兴趣和自己用而做的，不会加广告和收费。
