### ISSUE TITLE
对动图或者视频的预览常常导致页面卡死

### ISSUE THREAD

**Issue by Asahey** [Ocrosoft/PixivPreviewer#37]
如题，鼠标有时候移到视频上就自动开始预览，然后必然导致页面无响应

**Comment by Ocrosoft** [comment]
相同问题：https://github.com/Ocrosoft/PixivPreviewer/issues/27
master 版本已经调整了动图加载的方式，应该能修复这个问题。

**Comment by Ocrosoft** [comment]
先关闭 issue，如果还有问题可重新打开
