### ISSUE TITLE
[建议]希望使用手机访问pixiv时，也能够使用该插件功能

### ISSUE THREAD

**Issue by madlife12327** [Ocrosoft/PixivPreviewer#39]
安卓系统，使用yandex浏览器安装了作者大大的插件

这是手机用手机模式访问pixiv时插件使用情况:
![Screenshot_20240219-214815__01](https://github.com/Ocrosoft/PixivPreviewer/assets/44774110/705e2df1-1f0e-42a9-abc4-74ff53bdc646)

这是手机用浏览器的电脑模式访问pixiv时插件使用情况:
![Screenshot_20240219-214857__01__01](https://github.com/Ocrosoft/PixivPreviewer/assets/44774110/ab852741-61f0-4ca5-b668-71f45593efd4)

可以看到手机模式访问pixiv时，插件没有起作用，而使用浏览器的电脑模式访问pixiv时，插件起作用了

希望作者大大可以完善一下功能，使其能够在手机模式访问pixiv的情况下，也能使用插件功能，感谢～

**Comment by Ocrosoft** [comment]
这个之前 greasyfork 上有提过，但是移动版的适配改动很大，目前没有这个打算。
我之前在手机上使用是使用浏览器的桌面版网页来查看的，但是需要放大缩小才能看清。

**Comment by madlife12327** [comment]
原来如此，感谢
