### ISSUE TITLE
[BUG] 切换下一张预览图会同时使得页面向下卷轴

### ISSUE THREAD

**Issue by WntFlm** [Ocrosoft/PixivPreviewer#43]
此前，当鼠标悬停在预览窗格上滚动鼠标滚轮时，会切换下一张预览图，同时固定页面不滑动。
之前的更新后虽然修复了预览窗格显示问题，但是这个功能似乎没有修复。现在切换预览页的同时还会使得页面整体下滑，影响浏览。

**Comment by Ocrosoft** [comment]
Edge 下正常，是浏览器兼容问题？

**Comment by WntFlm** [comment]
我的问题，我忘了最近装了 smoothscroll
