### ISSUE TITLE
部分账号的发现页预览好像挂了

### ISSUE THREAD

**Issue by lin65254154** [Ocrosoft/PixivPreviewer#44]
试了4个账号,有两个触发不了脚本
![image](https://github.com/user-attachments/assets/f4bde5d1-db58-4730-9a17-0ac8388b889f)

**Comment by Ocrosoft** [comment]
看起来没加载，可能url的问题

**Comment by Ocrosoft** [comment]
https://www.pixiv.net/discovery

**Comment by lin65254154** [comment]
![image](https://github.com/user-attachments/assets/b9116895-217c-42b3-a3c3-92a6bf637ad2)
完整链接貌似也不行

**Comment by Ocrosoft** [comment]
找到问题了，有时会找不到根节点，所以没成功加载，已经修复
