### ISSUE TITLE
始终Get toolbar failed.

### ISSUE THREAD

**Issue by PYUDNG** [Ocrosoft/PixivPreviewer#5]
稍微加debugger跟了一下，在gettoolbarfailed的时候console.log(findToolbarCommon)输出undefined。在页面加载完毕后手动 $('#root>div>div>ul').get(0) 是可以获取到toolbar的
目前观察到首页和illustration页都有此问题，并且由于此问题，自动排序功能无法使用。
在任何页面，右下角黑色圆形设置按钮都可以正常显示。
已经在Greasyfork上反馈，并附有图片：https://greasyfork.org/zh-CN/scripts/30766-pixiv-previewer/discussions/71699#comment-179422

**Comment by Ocrosoft** [comment]
设置按钮正常显示说明获取到了右下角的位置。
这个问题很难确定，尝试一下关闭其他脚本，然后再试一次。
我尝试了85.0.2版本的firefox并没有出现问题。
