### ISSUE TITLE
是不支持1000页以后的爬图吗？

### ISSUE THREAD

**Issue by shenzhizxz** [Ocrosoft/PixivPreviewer#6]
例如，当按收藏排序1001到1010页的作品时，获取收藏数时会在60/600卡住，同时下侧用于翻页的<previewer>中的“>”（右侧翻页键）也会消失

**Comment by Ocrosoft** [comment]
确实，之后查一下

**Comment by Ocrosoft** [comment]
p站没有1001页的（不排除需要开会员）
脚本拉取到的1000页以后的数据与第1000页相同，重复数据导致加载失败，v3.4.3已修复，greasyfork稍后更新。
