### ISSUE TITLE
脚本经常无法使用

### ISSUE THREAD

**Issue by ZeroTwo-02** [Ocrosoft/PixivPreviewer#7]

**Comment by Ocrosoft** [comment]
感觉大部分错误都跟jQuery的CDN访问不了有关系
就算是换其他cdn，总有人会访问不了，难搞

**Comment by ZeroTwo-02** [comment]
> 感觉大部分错误都跟jQuery的CDN访问不了有关系
> 就算是换其他cdn，总有人会访问不了，难搞

难搞哦，脚本崩溃时的P站真能裂开。。。还是看运气吧，会议结束了，应该放宽一些了

**Comment by North-glory** [comment]
脚本无法正常使用，tampermonkey右下角标了1，提示脚本在运行，但是没有效果。

**Comment by Ocrosoft** [comment]
> 脚本无法正常使用，tampermonkey右下角标了1，提示脚本在运行，但是没有效果。

https://github.com/Ocrosoft/PixivPreviewer/raw/master/pixiv%20previewer.user.js
可以安装master版本试试。

**Comment by ZeroTwo-02** [comment]
> > 脚本无法正常使用，tampermonkey右下角标了1，提示脚本在运行，但是没有效果。
> 
> https://github.com/Ocrosoft/PixivPreviewer/raw/master/pixiv%20previewer.user.js
> 可以安装master版本试试。

虽然大佬给的链接我打不开，但更新至3.6.1就能打开了，谢谢大佬！
