### ISSUE TITLE
「Feature Request」当按下按键时显示预览图

### ISSUE THREAD

**Issue by BoruiGu** [Ocrosoft/PixivPreviewer#9]
希望可以新增一个设置只有当按下某个按键时立即显示当前鼠标悬浮位置作品的预览图，否则则不显示预览图

这样用户可以准确的控制何时显示预览

**Comment by Ocrosoft** [comment]
> 希望可以新增一个设置只有当按下某个按键时立即显示当前鼠标悬浮位置作品的预览图，否则则不显示预览图
> 
> 这样用户可以准确的控制何时显示预览

三个鼠标按键都不太合适，键盘又不太方便。
如果有比较合适的方案，可以加上这个功能。

**Comment by BoruiGu** [comment]
这样如何？
* ”常时预览“与”按下ctrl显示预览“无法同时开启，可以二选一或者都关闭
* 当”常时预览“开启时可以设置”预览延迟（毫秒）“，包括ctrl键的用法皆与现有功能一致
* 当”常时预览“关闭时无法设置”预览延迟（毫秒）“
* 当”按下ctrl显示预览“开启时只有当按下ctrl键立即显示预览

<img width="463" alt="Image on 2021-11-11 06 05 14 AM" src="https://user-images.githubusercontent.com/8686167/141287638-dbb5472f-8c5b-4671-9a73-57b00d925c12.png">

**Comment by Ocrosoft** [comment]
> 这样如何？
> 
> * ”常时预览“与”按下ctrl显示预览“无法同时开启，可以二选一或者都关闭
> * 当”常时预览“开启时可以设置”预览延迟（毫秒）“，包括ctrl键的用法皆与现有功能一致
> * 当”常时预览“关闭时无法设置”预览延迟（毫秒）“
> * 当”按下ctrl显示预览“开启时只有当按下ctrl键立即显示预览
> 
> <img alt="Image on 2021-11-11 06 05 14 AM" width="463" src="https://user-images.githubusercontent.com/8686167/141287638-dbb5472f-8c5b-4671-9a73-57b00d925c12.png">

master现在加了这个功能，可以点击以下链接安装，如果没有什么bug，一周后同步到greasyfork的正式版中。
https://github.com/Ocrosoft/PixivPreviewer/raw/master/pixiv%20previewer.user.js
